<a href="https://colab.research.google.com/github/amitsingh6261/Machine_learning/blob/main/col_transformer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

df = pd.DataFrame({
    'Age': [20, 21, 22, 20, 23, 21],
    'CGPA': [7.5, 8.2, 9.0, 6.8, 8.7, 7.2],
    'Gender': ['Male', 'Female', 'Male', 'Female', 'Male', 'Female'],
    'Branch': ['CSE', 'ECE', 'CSE', 'ME', 'CSE', 'ECE'],
    'Placed': [1, 1, 1, 0, 1, 0]
})

In [2]:
X = df.drop('Placed', axis=1)
y = df['Placed']

In [3]:
x_train, x_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [5]:
x_train

   Age  CGPA  Gender Branch
5   21   7.2  Female    ECE
2   22   9.0    Male    CSE
4   23   8.7    Male    CSE
3   20   6.8  Female     ME

In [7]:
x_test

   Age  CGPA  Gender Branch
0   20   7.5    Male    CSE
1   21   8.2  Female    ECE

In [8]:
transformer = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['Age', 'CGPA']),
        ('cat', OneHotEncoder(handle_unknown='ignore'),
         ['Gender', 'Branch'])
    ]
)

In [9]:
x_train_transformed = transformer.fit_transform(x_train)
x_test_transformed = transformer.transform(x_test)

print(x_train_transformed)
print(x_test_transformed)

[[-0.4472136  -0.76985122  1.          0.          0.          1.
   0.        ]
 [ 0.4472136   1.14150353  0.          1.          1.          0.
   0.        ]
 [ 1.34164079  0.8229444   0.          1.          1.          0.
   0.        ]
 [-1.34164079 -1.19459671  1.          0.          0.          0.
   1.        ]]
[[-1.34164079 -0.45129209  0.          1.          1.          0.
   0.        ]
 [-0.4472136   0.29201253  1.          0.          0.          1.
   0.        ]]