<a href="https://colab.research.google.com/github/amitsingh6261/Machine_learning/blob/main/OHE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
import pandas as pd
import numpy as np

In [56]:
df=pd.read_csv("/content/car_dataset_555.csv")

In [57]:
df

       Brand  KM_Driven   Owner    Fuel  Selling_Price
0    Hyundai      13278   Third  Diesel         473008
1    Renault      21395   Third  Diesel         401978
2    Renault      88907   First     CNG         346178
3        Kia      38893  Second     CNG         599864
4        Kia      54597  Second  Petrol         551092
..       ...        ...     ...     ...            ...
550  Hyundai      99538  Second  Petrol         324646
551     Ford      18783   First  Diesel         431588
552   Toyota      78116  Second  Petrol         570055
553  Hyundai      64321   First  Petrol         467422
554  Hyundai      23845   Third  Petrol         412943

[555 rows x 5 columns]

In [58]:
df['Owner'].value_counts()

Owner
Third     204
Second    191
First     160
Name: count, dtype: int64

In [59]:
# using pandas OHE

pd.get_dummies(df,columns=['Fuel','Owner'],dtype=int)

,Brand,KM_Driven,Selling_Price,Fuel_CNG,Fuel_Diesel,Fuel_Petrol,Owner_First,Owner_Second,Owner_Third
0,Hyundai,13278,473008,0,1,0,0,0,1
1,Renault,21395,401978,0,1,0,0,0,1
2,Renault,88907,346178,1,0,0,1,0,0
3,Kia,38893,599864,1,0,0,0,1,0
4,Kia,54597,551092,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...
550,Hyundai,99538,324646,0,0,1,0,1,0
551,Ford,18783,431588,0,1,0,1,0,0
552,Toyota,78116,570055,0,0,1,0,1,0
553,Hyundai,64321,467422,0,0,1,1,0,0
554,Hyundai,23845,412943,0,0,1,0,0,1

In [60]:
# k-1 OHE

pd.get_dummies(df,columns=['Fuel','Owner'],dtype=int,drop_first=True)

,Brand,KM_Driven,Selling_Price,Fuel_Diesel,Fuel_Petrol,Owner_Second,Owner_Third
0,Hyundai,13278,473008,1,0,0,1
1,Renault,21395,401978,1,0,0,1
2,Renault,88907,346178,0,0,0,0
3,Kia,38893,599864,0,0,1,0
4,Kia,54597,551092,0,1,1,0
...,...,...,...,...,...,...,...
550,Hyundai,99538,324646,0,1,1,0
551,Ford,18783,431588,1,0,0,0
552,Toyota,78116,570055,0,1,1,0
553,Hyundai,64321,467422,0,1,0,0
554,Hyundai,23845,412943,0,1,0,1

In [61]:
from sklearn.model_selection import train_test_split

In [62]:
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2,random_state=42)

In [63]:
x_train

          Brand  KM_Driven   Owner    Fuel
140    Mahindra      25396   Third  Petrol
89   Volkswagen      83975   Third  Petrol
310         Kia      75774   Third  Diesel
499     Hyundai      21851   First     CNG
155         Kia      84177   Third  Petrol
..          ...        ...     ...     ...
71         Ford      70946  Second  Diesel
106     Hyundai      41635   Third  Diesel
270         Kia      51207   Third  Diesel
435      Toyota      32047  Second     CNG
102  Volkswagen      80539  Second  Diesel

[444 rows x 4 columns]

In [64]:
x_test

          Brand  KM_Driven   Owner    Fuel
231         Kia      26901   Third     CNG
374      Maruti      10836  Second  Petrol
55   Volkswagen      82420   First  Diesel
381      Maruti      22255  Second  Diesel
70       Maruti      49829  Second  Petrol
..          ...        ...     ...     ...
11         Tata      31417  Second  Diesel
281     Hyundai      77908   First  Diesel
22      Renault      79514   First     CNG
375      Maruti      38668   Third  Diesel
477       Honda      58741   First     CNG

[111 rows x 4 columns]

In [65]:
y_train

140    497385
89     355443
310    559108
499    539567
155    539890
        ...
71     304181
106    433635
270    598583
435    675551
102    453650
Name: Selling_Price, Length: 444, dtype: int64

In [66]:
# ohe using sklearn

from sklearn.preprocessing import OneHotEncoder

In [67]:
ohe=OneHotEncoder(drop='first',sparse_output=False,dtype=np.int32)

In [68]:
x_train_new= ohe.fit_transform(x_train[['Fuel','Owner']])

In [69]:
x_test_new=ohe.transform(x_test[['Fuel','Owner']])

In [70]:
x_train_new.shape

(444, 4)

In [71]:
np.hstack((x_train[['Brand','KM_Driven']].values,x_train_new))

array([['Mahindra', 25396, 0, 1, 0, 1],
       ['Volkswagen', 83975, 0, 1, 0, 1],
       ['Kia', 75774, 1, 0, 0, 1],
       ...,
       ['Kia', 51207, 1, 0, 0, 1],
       ['Toyota', 32047, 0, 0, 1, 0],
       ['Volkswagen', 80539, 1, 0, 1, 0]], dtype=object)

In [72]:
# ohe with top categories

counts= df['Brand'].value_counts()

In [73]:
df['Brand'].nunique()
threshold=100

In [74]:
repl=counts[counts<=threshold].index

In [76]:
pd.get_dummies(df['Brand'].replace(repl,'uncomon'),dtype=int)

     uncomon
0          1
1          1
2          1
3          1
4          1
..       ...
550        1
551        1
552        1
553        1
554        1

[555 rows x 1 columns]